name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint and Format Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm install --legacy-peer-deps -D eslint@8.x prettier@2.x @typescript-eslint/parser@6.x @typescript-eslint/eslint-plugin@6.x

      - name: Run ESLint
        continue-on-error: true
        run: npx eslint --max-warnings 50 --ext .js,.jsx,.ts,.tsx ./

      - name: Run Prettier Check
        continue-on-error: true
        run: npx prettier --check .

      - name: Type Check
        run: npx tsc --noEmit --skipLibCheck

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm install --legacy-peer-deps -D jest@29.x @testing-library/react@14.x @testing-library/jest-dom@6.x

      - name: Setup Test Environment
        run: |
          touch .env.test
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.test
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.test

      - name: Run Tests
        run: npm test || true

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Setup Build Environment
        run: |
          touch .env.production
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env.production
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env.production

      - name: Build Application
        run: npm run build

      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: .next/

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run npm audit
        continue-on-error: true
        run: |
          npm audit fix || true
